[build-system]
requires = ["setuptools>=60.0"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = "-raXs --durations 10 --color=yes --doctest-modules"
testpaths = [
    "tests/",
]
filterwarnings = [
    "error",
]
